server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:5048
          predicates:
            - Path=/api/auth/**
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/orders/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:5048
          predicates:
            - Path=/api/auth/**
        - id: product-service
          uri: http://product-service:8081
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/api/orders/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info