server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:5048
          predicates:
            - Path=/api/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:5001
          predicates:
            - Path=/api/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/